#!/bin/bash
set -e

# ═══════════════════════════════════════════════════════════════════
# IronClaw Railway Template — start.sh (NullClaw Edition)
# Automatically writes .env from Railway env vars and starts IronClaw
# No Telegram or manual onboard required.
# ═══════════════════════════════════════════════════════════════════

LOCKFILE="/tmp/start.sh.lock"
if [ -f "$LOCKFILE" ]; then
    EXISTING_PID=$(cat "$LOCKFILE" 2>/dev/null)
    if [ -n "$EXISTING_PID" ] && [ "$EXISTING_PID" != "$$" ] && [ "$EXISTING_PID" != "1" ] && kill -0 "$EXISTING_PID" 2>/dev/null; then
        echo "start.sh already running (PID: $EXISTING_PID). Exiting."
        exit 0
    fi
fi
echo $$ > "$LOCKFILE"
trap "rm -f $LOCKFILE" EXIT

# Kill any stale ironclaw process
if pgrep -x ironclaw > /dev/null 2>&1; then
    echo "WARNING: Stale ironclaw process found. Killing."
    pkill -x ironclaw || true
    sleep 1
fi

ENV_FILE="/data/.ironclaw/.env"
mkdir -p /data/.ironclaw /data/.ironclaw/logs /data/.npm-global /data/.npm-cache

# npm persistent storage
npm config set prefix '/data/.npm-global'
npm config set cache '/data/.npm-cache'

# Activate Homebrew
eval "$(/data/.linuxbrew/bin/brew shellenv)" 2>/dev/null || true

# ─── Write .env from Railway env vars ────────────────────────────
echo "Writing IronClaw config from environment variables..."
cat > "$ENV_FILE" <<EOF
# IronClaw config — auto-generated by start.sh
DATABASE_BACKEND=${DATABASE_BACKEND:-libsql}

# LLM Provider
LLM_BACKEND=${LLM_BACKEND:-anthropic}
LLM_API_KEY=${LLM_API_KEY}
LLM_MODEL=${LLM_MODEL:-claude-sonnet-4-20250514}

# Agent
AGENT_NAME=ironclaw
CLI_ENABLED=false

# Web Gateway
GATEWAY_ENABLED=true
GATEWAY_HOST=0.0.0.0
GATEWAY_PORT=8080
GATEWAY_AUTH_TOKEN=${GATEWAY_AUTH_TOKEN}

# Features
SANDBOX_ENABLED=false
HEARTBEAT_ENABLED=false
EMBEDDING_ENABLED=false

# Docker
IRONCLAW_IN_DOCKER=true
IRONCLAW_RESTART_DELAY=5
IRONCLAW_MAX_FAILURES=10
EOF

echo ".env written to $ENV_FILE"

# Validate required vars
if [ -z "$LLM_API_KEY" ]; then
    echo "ERROR: LLM_API_KEY is not set. Please add it in Railway Variables."
    exit 1
fi
if [ -z "$GATEWAY_AUTH_TOKEN" ]; then
    echo "ERROR: GATEWAY_AUTH_TOKEN is not set. Please add it in Railway Variables."
    exit 1
fi

# ─── Install default WASM extensions ─────────────────────────────
TOOLS_DIR="/data/.ironclaw/tools"
if [ -d "$TOOLS_DIR" ] && ls "$TOOLS_DIR"/*.wasm 1>/dev/null 2>&1; then
    echo "Extensions already installed, skipping."
else
    echo "Installing default extensions..."
    ironclaw registry install-defaults --force 2>&1 || echo "Warning: some extensions failed (non-fatal)"
fi

# ─── Start IronClaw ───────────────────────────────────────────────
echo "Starting IronClaw gateway on port 8080..."
exec ironclaw --no-onboard
